version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=REPLACE_ME_you_likely_dont_need_this_in_dev_REPLACE_ME
      - AWS_SECRET_ACCESS_KEY=REPLACE_ME_you_likely_dont_need_this_in_dev_REPLACE_ME
      - AWS_BUCKET_NAME=REPLACE_ME_you_likely_dont_need_this_in_dev_REPLACE_ME
      - PORT=3531
    ports:
      - 3531:3531
    volumes:
      - ./src:/src
